export enum ROUTES {
  HOME = '/',
  RESET = '/reset',
  ACCOUNT = '/account',
  ADDRESSES = '/addresses',
  SHOP = '/shop',
  DASHBOARD = '/dashboard',
  CART = '/cart',
  PRODUCTS = '/products',
  COUPONS = '/coupons',
  SALES = '/sales',
  ORDERS = '/orders',
  CHECKOUT = '/checkout',
  SUCCESS = '/success',
  NEW = '/new',
}
